export const CHANGE_NAV_ACTIVE = 'nav/change_nav_active'
export const CHANGE_OVERALL_DATA = 'map/change_overall_data'
export const CHANGE_NEWS_DATA = 'map/change_news_data'
export const CHANGE_RUMOR_DATA = 'map/change_rumor_data'
export const CHANGE_HEADER_HEIGHT = 'map/change_header_height'
export const CHANGE_NEWS_HEIGHT = 'map/change_news_height'
export const CHANGE_RUMOR_HEIGHT = 'map/change_rumor_height'